POST localhost:8080/query
ontent-Type: application/json

{
    # "query": "CREATE TABLE music(num int primary key, tipo char(8), cantantes int, score double);"
    # "query": "INSERT INTO music from 'data2';"
    "query": "SELECT * FROM mus;"
}
    # "query": "DROP TABLE music;"
